NAME = megaphone
SRCS = megaphone.cpp
CMP = c++
FLAGS = -Wall -Wextra -Werror -std=c++98

all:$(NAME)

$(NAME):
	$(CMP) $(FLAGS) $(SRCS) -o $(NAME)

clean:
	rm -f $(NAME)

fclean : clean

re: fclean all